[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.9.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"
